version: '3.8'
services:
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: mslabs.1
    volumes:
      - sailpoint-iiq-db:/var/lib/mysql:rw
  iiq:
    build:
      context: .
      dockerfile: ./sailpoint-iiq/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=mslabs.1
      - MYSQL_HOST=db
      - IIQ_VERSION=8.3
      - IIQ_PATCH=8.3p1
volumes:
  sailpoint-iiq-db: